### ISSUE TITLE
页面切换时报错

### ISSUE THREAD

**Issue by pershow** [panyiho/flutter_quick_template#1]
I/flutter ( 4132): "MineLogic" not found. You need to call "Get.put(MineLogic())" or "Get.lazyPut(()=>MineLogic())"
I/flutter ( 4132): 
I/flutter ( 4132): When the exception was thrown, this was the stack:
I/flutter ( 4132): #0      GetInstance.find (package:get/get_instance/src/get_instance.dart:306:7)
I/flutter ( 4132): #1      GetView.controller (package:get/get_state_manager/src/simple/get_view.dart:38:37)
I/flutter ( 4132): #2      BasePage.build.<anonymous closure> (package:perlefect/core/base/base_page.dart:21:15)
I/flutter ( 4132): #3      _LifecycleWrapperState.onLifecycleEvent (package:lifecycle/src/lifecycle_wrapper.dart:33:28)
I/flutter ( 4132): #4      LifecycleAware.handleLifecycleEvents (package:lifecycle/src/lifecycle_aware.dart:43:9)
I/flutter ( 4132): #5      LifecycleMixin.dispose (package:lifecycle/src/lifecycle_mixin.dart:53:5)
I/flutter ( 4132): #6      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5689:11)
I/flutter ( 4132): #7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2076:13)
I/flutter ( 4132): #8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
I/flutter ( 4132): #9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
I/flutter ( 4132): #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
I/flutter ( 4132): #11     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
I/flutter ( 4132): #12     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2085:25)
I/flutter ( 4132): #13     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2764:15)
I/flutter ( 4132): #14     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3174:7)
I/flutter ( 4132): #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:992:19)
I/flutter ( 4132): #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
I/flutter ( 4132): #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
I/flutter ( 4132): #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
I/flutter ( 4132): #19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
I/flutter ( 4132): #20     _invoke (dart:ui/hooks.dart:312:13)
I/flutter ( 4132): #21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
I/flutter ( 4132): #22     _drawFrame (dart:ui/hooks.dart:283:31)

**Comment by pershow** [comment]
解决了，改成这样：

```
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';
import 'package:lifecycle/lifecycle.dart';

import 'base_controller.dart';

abstract class BasePage<T extends BaseController> extends GetView<T> {
  BuildContext? context;
  T generateController();
  @override
  Widget build(BuildContext context) {
    this.context = context;
    Get.put(generateController());
    return LifecycleWrapper(
        onLifecycleEvent: (LifecycleEvent lifecycleEvent) {
          switch (lifecycleEvent) {
            case LifecycleEvent.visible:
              if (Get.isRegistered<T>()) controller.onPageVisible();
              break;
            case LifecycleEvent.inactive:
              if (Get.isRegistered<T>()) controller.onPageInActive();
              break;
            case LifecycleEvent.active:
              if (Get.isRegistered<T>()) controller.onPageActive();
              break;
            case LifecycleEvent.invisible:
              if (Get.isRegistered<T>()) controller.onPageInVisible();
              break;
            default:
          }
        },
        child: GetBuilder<T>(builder: buildWidget, assignId: true));
  }

  Widget buildWidget(T controller);
}

```
